### ISSUE TITLE
(Bug report) v0.90.4 docker does not read USER_UID and USER_GID from environment

### ISSUE THREAD

**Issue by yu-jingrui** [TriliumNext/Notes#331]
### TriliumNext Version

0.90.4

### What operating system are you using?

Windows

### What is your setup?

Local + server sync

### Operating System Version

windows 11

### Description

Docker server is deployed on synology DS920+ with container manager. After updating to 0.90.4 from 0.94.3, the docker instance shuts down with error code -13. It keeps setting uid and gid to 1000 although they are specified in environment. Here is the compose file:
```
version: "3"
services:
  trilium:
    image: triliumnext/notes:v0.90.4
    container_name: triliumnext
    restart: unless-stopped
    hostname: triliumnext
    volumes:
      - ./trilium-data:/home/node/trilium-data
    environment:
      USER_UID: xxxx
      USER_GID: xxxxx
    ports:
      - xxxxx:8080
```

### Error logs

2024/8/11 16:09	stderr	Node.js v20.15.1	
2024/8/11 16:09	stderr
2024/8/11 16:09	stderr	}
2024/8/11 16:09	stderr	  path: '/home/node/trilium-data/log'
2024/8/11 16:09	stderr	"  syscall: 'mkdir',"
2024/8/11 16:09	stderr	"  code: 'EACCES',"
2024/8/11 16:09	stderr	"  errno: -13,"
2024/8/11 16:09	stderr	    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
2024/8/11 16:09	stderr	    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
2024/8/11 16:09	stderr	    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
2024/8/11 16:09	stderr	    at file:///usr/src/app/src/services/log.js:6:8
2024/8/11 16:09	stderr	    at Object.mkdirSync (node:fs:1372:26)
2024/8/11 16:09	stderr	"Error: EACCES: permission denied, mkdir '/home/node/trilium-data/log'"
2024/8/11 16:09	stderr	
2024/8/11 16:09	stderr	                         ^
2024/8/11 16:09	stderr	  const result = binding.mkdir(
2024/8/11 16:09	stderr	node:fs:1372
2024/8/11 16:09	stderr	(Use `node --trace-warnings ...` to show where the warning was created)
2024/8/11 16:09	stderr	(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
2024/8/11 16:09	stdout	"No USER_GID specified, leaving 1000"
2024/8/11 16:09	stdout	"No USER_UID specified, leaving 1000"
2024/8/11 16:09	stderr	./start-docker.sh: 4: [[: not found
2024/8/11 16:09	stderr	./start-docker.sh: 3: [[: not found
2024/8/11 16:09	stderr	Node.js v20.15.1
2024/8/11 16:09	stderr	
2024/8/11 16:09	stderr	}
2024/8/11 16:09	stderr	  path: '/home/node/trilium-data/log'
2024/8/11 16:09	stderr	"  syscall: 'mkdir',"
2024/8/11 16:09	stderr	"  code: 'EACCES',"
2024/8/11 16:09	stderr	"  errno: -13,"
2024/8/11 16:09	stderr	    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
2024/8/11 16:09	stderr	    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
2024/8/11 16:09	stderr	    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
2024/8/11 16:09	stderr	    at file:///usr/src/app/src/services/log.js:6:8
2024/8/11 16:09	stderr	    at Object.mkdirSync (node:fs:1372:26)
2024/8/11 16:09	stderr	"Error: EACCES: permission denied, mkdir '/home/node/trilium-data/log'"
2024/8/11 16:09	stderr	
2024/8/11 16:09	stderr	                         ^
2024/8/11 16:09	stderr	  const result = binding.mkdir(
2024/8/11 16:09	stderr	node:fs:1372
2024/8/11 16:09	stderr	(Use `node --trace-warnings ...` to show where the warning was created)
2024/8/11 16:09	stderr	(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
2024/8/11 16:09	stdout	"No USER_GID specified, leaving 1000"
2024/8/11 16:09	stdout	"No USER_UID specified, leaving 1000"
2024/8/11 16:09	stderr	./start-docker.sh: 4: [[: not found
2024/8/11 16:09	stderr	./start-docker.sh: 3: [[: not found

**Comment by eliandoran** [comment]
@yu-jingrui , thank you for the detailed report.

I believe this got broken when we switched from `alpine` to `debian-slim` due to issues with ARM builds.

I've pushed a fix to `develop`. If you have the time to check: https://hub.docker.com/layers/triliumnext/notes/develop/images/sha256-54b46770713f9bae776f2bf45d7bdcf524eeee94c5dd0421634b6d0b5133fd90?context=repo

If not, you could always fall back to an older version and move to the next stable release, which I think will only come in a few weeks (we'll release some betas for internationalization first).

**Comment by yu-jingrui** [comment]
> @yu-jingrui , thank you for the detailed report.
> 
> I believe this got broken when we switched from `alpine` to `debian-slim` due to issues with ARM builds.
> 
> I've pushed a fix to `develop`. If you have the time to check: https://hub.docker.com/layers/triliumnext/notes/develop/images/sha256-54b46770713f9bae776f2bf45d7bdcf524eeee94c5dd0421634b6d0b5133fd90?context=repo
> 
> If not, you could always fall back to an older version and move to the next stable release, which I think will only come in a few weeks (we'll release some betas for internationalization first).

I tried develop and it seems to be working correctly. Thanks for the quick fix. I will wait for the next stable release and use 0.90.3 for the moment.

**Comment by l-33ter** [comment]
TriliumNext Version
0.90.4

What operating system are you using?
Debian12

Yes, I encountered the same error as well. I haven't attempted your fix on the `develop` branch yet; I want to type out the error first.

```yaml
# https://github.com/TriliumNext/Notes
# Running `docker-compose up` will create/use the "trilium-data" directory in the user home
# Run `TRILIUM_DATA_DIR=/path/of/your/choice docker-compose up` to set a different directory
# To run in the background, use `docker-compose up -d`
services:
  trilium:
    # Optionally, replace `latest` with a version tag like `v0.90.3`
    # Using `latest` may cause unintended updates to the container
    image: triliumnext/notes:v0.90.4
    container_name: triliumnext-notes
    # Restart the container unless it was stopped by the user
    restart: unless-stopped
    environment:
      TRILIUM_DATA_DIR: ${TRILIUM_DATA_DIR}
      USER_UID: ${USER_UID}
      USER_GID: ${USER_GID}
    ports:
      # By default, Trilium will be available at http://localhost:8080
      # It will also be accessible at http://<host-ip>:8080
      # You might want to limit this with something like Docker Networks, reverse proxies, or firewall rules, such as UFW
      - '9991:8080'
    networks:
      - proxy
    volumes:
      # Unless TRILIUM_DATA_DIR is set, the data will be stored in the "trilium-data" directory in the home directory.
      # This can also be changed with by replacing the line below with `- /path/of/your/choice:/home/node/trilium-data
      - ${TRILIUM_DATA_DIR:-~/trilium-data}:/home/node/trilium-data

networks:
  proxy:
    external: true
```

```Node.js v20.15.1
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
./start-docker.sh: 3: [[: not found
./start-docker.sh: 4: [[: not found
(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:fs:1372
  const result = binding.mkdir(
                         ^

Error: ENOENT: no such file or directory, mkdir '/home/mrcl/Adocker/Project-TEST/August_2024/TriliumNext/my-data/'
    at Object.mkdirSync (node:fs:1372:26)
    at getTriliumDataDir (file:///usr/src/app/src/services/data_dir.js:33:16)
    at file:///usr/src/app/src/services/data_dir.js:47:26
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/mrcl/Adocker/Project-TEST/August_2024/TriliumNext/my-data/'
}

Node.js v20.15.1
./start-docker.sh: 3: [[: not found
./start-docker.sh: 4: [[: not found
No USER_UID specified, leaving 1000
No USER_GID specified, leaving 1000
(node:9) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:fs:1372
  const result = binding.mkdir(
                         ^

Error: ENOENT: no such file or directory, mkdir '/home/mrcl/Adocker/Project-TEST/August_2024/TriliumNext/my-data/'
    at Object.mkdirSync (node:fs:1372:26)
    at getTriliumDataDir (file:///usr/src/app/src/services/data_dir.js:33:16)
    at file:///usr/src/app/src/services/data_dir.js:47:26
    at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:123:5) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/home/mrcl/Adocker/Project-TEST/August_2024/TriliumNext/my-data/'
}

Node.js v20.15.1
```

**Comment by PDiracDelta** [comment]
This bug still exists; I'm using triliumnext/notes:latest as of today (2024-12-30)
Please fix <3

**Comment by eliandoran** [comment]
@PDiracDelta , could you please provide more info? Is it the same issue as the OP, or is it something slightly different?

**Comment by PDiracDelta** [comment]
> @PDiracDelta , could you please provide more info? Is it the same issue as the OP, or is it something slightly different?

Indeed it's a bit different. To clarify, I'm talking about the issue mentioned in the last reply. Should I make a different ticket?

_... if I set TRILIUM_DATA_DIR (and I checked it before running docker compose with docker compose config that everything will be on their right places) - the container FAILED with the above error

However if I comment-out the TRILIUM_DATA_DIR and set the volumes directly ... Everything works perfectly clear!!_

**Comment by reinei** [comment]
I also experience the OPs problem (the initial one about not reading USER_UID) on the latest stable version of v0.92.7.

Technically, in my case the error happens when Trilium tries to make the `/tmp/` sub-directory in the `${TRILIUM_DATA_DIR}` which is volume mapped to a directory owned by the USER_UID of my host system, but seeing as the issue of not reading USER_UID (and even logging the fact it is apparently not set!) it appears to be the same issue.

**Comment by reinei** [comment]
Okay so yesterday I started dissecting the image/a container created from the image locally and debug-printed the entire passed environment. For some (to me still unknown) reason the environment was passed correctly and the usermod command is executed.

However, and **this is important for anyone else potentially having this issue in the future**, in my case the real culprit was SELinux on the host disallowing access to the mounted volume regardless of file permissions because the folder and all files were missing the `container_file_t` type description!
